name: sample-flow

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: java -version
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project,
        echo $JAVA_HOME
